### PR TITLE
return response body for 200, 201

### PR DESCRIPTION
**Pull request by thomhickey**

### CODE REVIEW

**Comment by thomhickey** [comment]
fixes #8

**Comment by monteledwards** [comment]
why just 200 or 201? should be 2**??

**Comment by thomhickey** [comment]
Sounds good, I can make that change. I hesitated at opening it up completely without knowing more about why only 200 bodies were let through before.

**Comment by thomhickey** [comment]
We only have a problem on success codes. Error codes return a proper response body. Let's decide on 2xx or 200/201 or whatever.

**Comment by lihaoyi** [comment]
0.1.6 is out

**Comment by thomhickey** [comment]
Thanks Haoyi! .. anything else I can help with here? I have some spare time.

**Pull request merged**
