### PR TITLE
Client certificate support

### LINKED ISSUE #12: Client Side Certificates
Are you planning to add support for client-side certificates similar to [requests](http://docs.python-requests.org/en/master/user/advanced/#client-side-certificates)? 
From my experience, the current Java API is very ugly and painful :)

### PR DESCRIPTION
**Pull request by Magua**
Added support for client certificate and key in p12 ([PKCS 12](https://en.wikipedia.org/wiki/PKCS_12)) format.

Initial plan was to support cert and key in plain text format but that is way harder, could always be added later. P12 should be familiar if you are on the JVM.

Used like this if p12 has password:
```
        val res = requests.get(
          "https://client.badssl.com",
          cert = ("badssl.com-client.p12", "badssl.com")
        )
```

And with no password:
```
        val res = requests.get(
          "https://client.badssl.com",
          cert = ("badssl.com-client.p12")
        )
```

- Can be combined with `verifySslCerts = false`.
- Supports p12 with and without password.

RFC
Closes #12

### CODE REVIEW

**Comment by fsanaulla** [comment]
Hi, @lihaoyi - any chance to merge it in the close time?
Thank you!

**Comment by debelyoo** [comment]
+1 for merging this PR

**Comment by lihaoyi** [comment]
Thanks!

**Comment by lihaoyi** [comment]
I had to revert this because it's giving me test failures on my laptop:
```
X requests.RequestTests.clientCertificate.passwordProtected 857ms
  utest.AssertionError: assert(res.statusCode == 200)
  res: requests.Response = Response(https://client.badssl.com,400,Bad Request,Map(server -> Buffer(nginx/1.10.3 (Ubuntu)), content-length -> Buffer(240), date -> Buffer(Sat, 21 Dec 2019 15:43:44 GMT), content-type -> Buffer(text/html), connection -> Buffer(close)),ResponseBlob(240 bytes),None)
    utest.asserts.Asserts$.assertImpl(Asserts.scala:116)
    requests.RequestTests$.$anonfun$tests$85(RequestTests.scala:214)
X requests.RequestTests.clientCertificate.noPassword 2139ms
  utest.AssertionError: assert(res.statusCode == 200)
  res: requests.Response = Response(https://client.badssl.com,400,Bad Request,Map(server -> Buffer(nginx/1.10.3 (Ubuntu)), content-length -> Buffer(240), date -> Buffer(Sat, 21 Dec 2019 15:43:46 GMT), content-type -> Buffer(text/html), connection -> Buffer(close)),ResponseBlob(240 bytes),None)
    utest.asserts.Asserts$.assertImpl(Asserts.scala:116)
    requests.RequestTests$.$anonfun$tests$87(RequestTests.scala:221)
```

**Pull request merged**
