### PR TITLE
Add Travis CI on the repo

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
This PR fails tests for Dotty since ujson is not yet published for Dotty.

### CODE REVIEW

**Comment by anatoliykmetyuk** [comment]
@lihaoyi do you know how to enable Travis CI on the branch of this PR? Or can we just merge it and let it fail on the main repo FTTB?

**Comment by lihaoyi** [comment]
@anatoliykmetyuk I flipped a switch on the travis website, I think that should make it enabled if you update this PR?

**Comment by anatoliykmetyuk** [comment]
It looks like upickle will have to be merged & published first.

**Comment by jodersky** [comment]
> It looks like upickle will have to be merged & published first.

I completed to upickle changes and submitted a PR https://github.com/lihaoyi/upickle/pull/322.

**Pull request merged**
