### PR TITLE
Client side certificate support

### PR DESCRIPTION
**Pull request by Magua**
Client certificate supported with PKSC 12 / pfx.

Use like this for password-less p12.
```scala
requests.get(
  "https://client.badssl.com",
  cert = "./badssl.com-client.p12"
)
```

Add password if necessary.
```scala
requests.get(
  "https://client.badssl.com",
  cert = ("./badssl.com-client.p12", "password")
)
```

badssl.com used in tests can and will occasionally (annually?) update certificates and that would fail the tests. Therefore I made the test print a warning in case of client certificate failure instead of failing the test.

Warning looks like this:

`WARNING: Certificate may have expired and needs to be updated. Please check: https://github.com/lihaoyi/requests-scala/blob/master/requests/test/resources/badssl.com-client.md and/or file issue`

### CODE REVIEW

**Comment by Magua** [comment]
Closes #12

**Comment by lionelfleury** [comment]
Nice work! :+1:

**Comment by Magua** [comment]
@lihaoyi have you had a chance to look at this, anything you want done differently?

**Comment by lihaoyi** [comment]
Sorry, i just haven't had a chance to take a look at this properly. I'll try to find time for a proper review soon!

**Comment by lihaoyi** [comment]
Looks good to me, sorry for the delay!

**Pull request merged**
